@extends('admin.layout.root')
@section('content')
@include('admin.layout.header')
<div class="admin-shell">@include('admin.layout.sidebar')<main class="admin-content">
<div class="mb-4"><h1>Game Lookup</h1><p class="mb-0 text-secondary">Search by an exact Place ID or game name.</p></div>
<section class="card bg-dark text-light border-secondary p-4 mb-4"><form method="GET" action="{{ route('admin.games.find') }}" class="row g-3 align-items-end"><div class="col-lg-9"><label class="form-label text-secondary fw-semibold" for="gameLookup">Place ID or Name</label><div class="input-group input-group-lg"><span class="input-group-text bg-dark border-secondary text-secondary"><i class="bi bi-search"></i></span><input id="gameLookup" name="q" value="{{ $query }}" class="form-control bg-dark border-secondary text-light" placeholder="For example: 1 or Crossroads"></div></div><div class="col-lg-3 d-grid"><button class="btn btn-primary btn-lg">Search games</button></div></form></section>
<section class="card bg-dark text-light border-secondary overflow-hidden"><div class="d-flex justify-content-between p-4 border-bottom border-secondary"><div><h2 class="h5 mb-1">{{ $query !== '' ? 'Search results' : 'All games' }}</h2><p class="text-secondary mb-0">{{ number_format($games->total()) }} games</p></div>@if($query !== '')<a href="{{ route('admin.games.find') }}" class="btn btn-sm btn-outline-light">Clear search</a>@endif</div>
<div class="table-responsive"><table class="table table-dark table-bordered table-striped align-middle mb-0"><thead class="text-secondary"><tr><th class="ps-4">Game</th><th>Creator</th><th>Players</th><th>Visits</th><th>Status</th><th class="text-end pe-4">Actions</th></tr></thead><tbody>
@forelse($games as $game)<tr><td class="ps-4"><div class="d-flex align-items-center gap-3"><img src="/Thumbs/Asset.ashx?assetId={{ $game->id }}" width="64" height="44" class="rounded object-fit-cover"><div><div class="fw-semibold">{{ $game->name }}</div><div class="small text-secondary">Place ID {{ $game->id }} · Universe {{ $game->universe_id ?? 'None' }}</div></div></div></td><td>{{ $game->creator?->username ?? '[unknown]' }} ({{ $game->creator_id }})</td><td>{{ $game->max_players }}</td><td>{{ number_format($game->visits) }}</td><td>@if($game->ghosted && $game->approval === \App\Models\Asset::APPROVAL_PENDING)<span class="badge text-bg-warning">Pending moderation</span>@elseif($game->ghosted)<span class="badge text-bg-danger">Deleted</span>@else<span class="badge text-bg-success">Active</span>@endif</td><td class="text-end pe-4"><a href="{{ route('admin.games.edit', $game) }}" class="btn btn-sm btn-outline-light">Edit Game</a></td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-secondary">No matching games.</td></tr>@endforelse
</tbody></table></div>@if($games->hasPages())<div class="p-4 border-top border-secondary">{{ $games->links() }}</div>@endif</section>
</main></div>@endsection
