<?php
use App\Http\Controllers\RBXApis\AC\ACLog;
use App\Http\Controllers\RBXApis\Ads\Sponsored;
use App\Http\Controllers\RBXApis\Asset;
use App\Http\Controllers\RBXApis\DStores;
use App\Http\Controllers\RBXApis\Feed;
use App\Http\Controllers\RBXApis\Friends\CountRequests;
use App\Http\Controllers\RBXApis\Friends\FriendService;
use App\Http\Controllers\RBXApis\Friends\Friends;
use App\Http\Controllers\RBXApis\Friends\SocialControls;
use App\Http\Controllers\RBXApis\Game\Joinscript;
use App\Http\Controllers\RBXApis\Game\PlaceLauncher;
use App\Http\Controllers\RBXApis\Game\StartGame;
use App\Http\Controllers\RBXApis\Game\Studio;
use App\Http\Controllers\RBXApis\Game\Whitelist;
use App\Http\Controllers\RBXApis\Games\Recommendations;
use App\Http\Controllers\RBXApis\Inventory\FetchAssets;
use App\Http\Controllers\RBXApis\Legacy\AssetComment;
use App\Http\Controllers\RBXApis\Locale;
use App\Http\Controllers\RBXApis\Legacy;
use App\Http\Controllers\RBXApis\Login\Negotiate;
use App\Http\Controllers\RBXApis\LuaWebService\HandleSocial;
use App\Http\Controllers\RBXApis\Marketplace\ProductInfo;
use App\Http\Controllers\RBXApis\Messages;
use App\Http\Controllers\RBXApis\Misc\Notification;
use App\Http\Controllers\RBXApis\Misc\Validation;
use App\Http\Controllers\RBXApis\Mobile\StaticResp;
use App\Http\Controllers\RBXApis\RCC\Analytics;
use App\Http\Controllers\RBXApis\RCC\CloseGameServer;
use App\Http\Controllers\RBXApis\RCC\KillLogger;
use App\Http\Controllers\RBXApis\RCC\ServerEntryLogger;
use App\Http\Controllers\RBXApis\Setting\AppSettings;
use App\Http\Controllers\RBXApis\Status;
use App\Http\Controllers\RBXApis\Thumbs\Batch;
use App\Http\Controllers\RBXApis\Universe\ValidateJoin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/Asset/BodyColors.ashx', [Legacy::class, 'bodyColors']);
Route::get('/Asset/CharacterFetch.ashx', [Asset::class, 'avatarFetch']);
Route::get('/asset', [Asset::class, 'serveAsset']);
Route::get('/Asset', [Asset::class, 'serveAsset']);
Route::match(['get', 'post'], 'api/thumbs/v1/batch', [Batch::class, 'getBatch']);
Route::match(['get', 'post'], '/mobileapi/check-app-version', [StaticResp::class, 'checkAppVersion']);
Route::match(['get', 'post'], '/device/initialize', [StaticResp::class, 'initializeDevice']);
Route::match(['get', 'post'], '/v1.0/SequenceStatistics/AddToSequence', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/v1.1/Counters/Increment', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/v1.0/SequenceStatistics/BatchAddToSequencesV2', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/v1.0/MultiIncrement', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/game/report-stats', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/usercheck/show-tos', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/notifications/signalr/negotiate', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/notifications/negotiate', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/v1.1/Counters/BatchIncrement', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/mobile/pbe', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/client/pbe', [StaticResp::class, 'telemetry']);
Route::get('/api/locale/v1/locales', [Locale::class, 'getLocale']);
Route::get('/api/locale/v1/locales/user-localization-locus-supported-locales', [Locale::class, 'getUserLocale']);
Route::post('/api/discovery-api/omni-recommendation', [Recommendations::class, 'omniSorts']);
Route::get('/users/friends/list-json', [Friends::class, 'getFriends']);
Route::post('/api/presence/v1/presence/users', [Status::class, 'getPresence']);
Route::get('/api/ads/v1/sponsored-pages', [Sponsored::class, 'get']);
Route::get('/api/privatemessages/v1/messages/unread/count', function () {
    return response()->json(['count' => '69']);
});
Route::get('/api/trades/v1/trades/inbound/count', function () {
    return response()->json(['count' => '69']);
});
Route::get('/api/friends/v1/user/friend-requests/count', [CountRequests::class, 'count']);
Route::get('/user/following-exists', [SocialControls::class, 'followingExists']);
Route::get('/user/get-friendship-count', [SocialControls::class, 'friendshipCount']);
Route::match(['get', 'post'], '/user/request-friendship', [SocialControls::class, 'requestFriendship']);
Route::post('/user/follow', [SocialControls::class, 'follow']);
Route::post('/api/user/unfollow', [SocialControls::class, 'unfollow']);
Route::get('/Friend/AreFriends', [FriendService::class, 'areFriends']);
Route::get('/Friend/AreFriends.ashx', [FriendService::class, 'areFriends']);
Route::get('/friend/arefriends', [FriendService::class, 'areFriends']);
Route::get('/friend/arefriends.ashx', [FriendService::class, 'areFriends']);
Route::get('/UserCheck/checkifinvalidusernameforsignup', [Validation::class, 'checkUsernameAvailability']);
Route::get('/UserCheck/doesusernameexist', [Validation::class, 'checkUserifexists']);
Route::get('/LunarixDefaultErrorPage.aspx', function (Request $request) {
    $code = (int) $request->query('code', 500);
    if ($code < 400 || $code > 599) {
        $code = 500;
    }
    return response()->view('ldef', ['code' => $code, 'ref' => $request->query('ref')], $code);
});
Route::post('/api/friends/sendfriendrequest', [SocialControls::class, 'addFriend']);
Route::post('/api/friends/removefriend', [SocialControls::class, 'removeFriend']);
Route::post('/api/friends/acceptfriendrequest', [SocialControls::class, 'acceptFriendRequest']);
Route::post('/api/friends/declinefriendrequest', [SocialControls::class, 'declineFriendRequest']);
Route::post('/feedifications/post', [Feed::class, 'post'])->middleware(['throttle:timeout']);
Route::get('/notifications/api/get-notifications', [Notification::class, 'index']);
Route::get('/messages/api/get-messages', [Messages::class, 'getMessages']);
Route::post('/messages/api/send-message', [Messages::class, 'sendMessage']);
Route::post('/messages/api/mark-messages-read', [Messages::class, 'markMessagesRead']);
Route::match(['get', 'post'], '/Game/PlaceLauncher.ashx', [PlaceLauncher::class, 'handle']);
Route::get('/games/start', [StartGame::class, 'handle']);
Route::get('/game/studio.ashx', [Studio::class, 'handle']);
Route::get('/Game/Studio.ashx', [Studio::class, 'handle']);
Route::get('/game/Studio.ashx', [Studio::class, 'handle']);
Route::match(['get', 'post'], '/Game/Join.ashx', [Joinscript::class, 'handle']);
Route::match(['get', 'post'], '/Login/Negotiate.ashx', [Negotiate::class, 'handle']);
Route::match(['get', 'post'], '/Login/NegotiateAsync.ashx', [Negotiate::class, 'handle']);
Route::match(['get', 'post'], '/Setting/QuietGet/ClientAppSettings', [AppSettings::class, 'client']);
Route::match(['get', 'post'], '/Setting/QuietGet/ClientSharedSettings', [AppSettings::class, 'shared']);
Route::match(['get', 'post'], '/Setting/QuietGet/AndroidAppSettings', [AppSettings::class, 'android']);
Route::match(['get', 'post'], '/Setting/QuietGet/RCCServiceaRWyf4zz9jy', [AppSettings::class, 'rcc']);
Route::match(['get', 'post'], '/Setting/QuietGet/XboxAppSettings', [AppSettings::class, 'xbox']);
Route::get('/GetAllowedMD5Hashes', [Whitelist::class, 'getAllowedMd5Hashes']);
Route::get('/GetAllowedSecurityVersions', [Whitelist::class, 'getAllowedSecurityVersions']);
Route::get('/GetAllowedSecurityKeys', [Whitelist::class, 'getAllowedSecurityKeys']);
Route::get('/universes/validate-place-join', [ValidateJoin::class, 'validate']);
Route::get('/asset/roblox', [Asset::class, 'serveRobloxAsset']);
Route::get('/Game/LuaWebService/HandleSocialRequest.ashx', [HandleSocial::class, 'handle']);
Route::get('/users/inventory/list-json', [FetchAssets::class, 'fetchJson']);
Route::get('/users/inventory/recommended-json', [FetchAssets::class, 'fetchRecommendedJson']);
Route::match(['get', 'post'], '/game/report-event', [StaticResp::class, 'telemetry']);
Route::match(['get', 'post'], '/client-status/set', [StaticResp::class, 'telemetry']);
Route::post('/RCCApi/Game/UserJoin', [ServerEntryLogger::class, 'userJoin']);
Route::post('/RCCApi/Game/UserExit', [ServerEntryLogger::class, 'userExit']);
Route::post('/RCCApi/Game/CloseJob', [CloseGameServer::class, 'closeGameServer']);
Route::post('/RCCApi/Stats/Update', [KillLogger::class, 'update']);
Route::post('/RCCApi/Analytics/Report', [Analytics::class, 'report']);
Route::post('/api/anticheat/log', [ACLog::class, 'log']);
Route::post('/api/comments.ashx', [AssetComment::class, 'legacyApi']);
Route::get('/comments/get-json', [AssetComment::class, 'getJson']);
Route::get('/marketplace/productinfo', [ProductInfo::class, 'productInfo']);
Route::get('/hos', function () {
    $path = storage_path('app/public/hos.txt');
    abort_unless(file_exists($path), 404);
    return response(file_get_contents($path), 200)->header('Content-Type', 'text/plain');
});
Route::get('/user/get-vote-count', function (Request $request) {
    return response()->json(['VoteCount' => 0]);
});
Route::post('/persistence/set', [DStores::class, 'set']);
Route::get('/persistence/increment', [DStores::class, 'increment']);
Route::match(['get', 'post'], '/persistence/getsorted', [DStores::class, 'getSorted']);
Route::match(['get', 'post'], '/persistence/getV2', [DStores::class, 'getV2']);